// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace johnharris85.Konnect
{
    /// <summary>
    /// Represents authentication settings
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Konnect = johnharris85.Konnect;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Konnect.AuthenticationSettings("example", new()
    ///     {
    ///         BasicAuthEnabled = true,
    ///         IdpMappingEnabled = false,
    ///         KonnectMappingEnabled = true,
    ///         OidcAuthEnabled = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Authentication settings can be imported using a proper value of `id` as described above
    /// </summary>
    [KonnectResourceType("konnect:index/authenticationSettings:AuthenticationSettings")]
    public partial class AuthenticationSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// **(Optional, Boolean)** Whether basic authentication is enabled.
        /// </summary>
        [Output("basicAuthEnabled")]
        public Output<bool?> BasicAuthEnabled { get; private set; } = null!;

        /// <summary>
        /// **(Optional, Boolean)** Whether IDP mapping is enabled.
        /// </summary>
        [Output("idpMappingEnabled")]
        public Output<bool?> IdpMappingEnabled { get; private set; } = null!;

        /// <summary>
        /// **(Optional, Boolean)** Whether Konnect mapping is enabled.
        /// </summary>
        [Output("konnectMappingEnabled")]
        public Output<bool?> KonnectMappingEnabled { get; private set; } = null!;

        /// <summary>
        /// **(Optional, Boolean)** Whether OIDC authentication is enabled.
        /// </summary>
        [Output("oidcAuthEnabled")]
        public Output<bool?> OidcAuthEnabled { get; private set; } = null!;


        /// <summary>
        /// Create a AuthenticationSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AuthenticationSettings(string name, AuthenticationSettingsArgs? args = null, CustomResourceOptions? options = null)
            : base("konnect:index/authenticationSettings:AuthenticationSettings", name, args ?? new AuthenticationSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AuthenticationSettings(string name, Input<string> id, AuthenticationSettingsState? state = null, CustomResourceOptions? options = null)
            : base("konnect:index/authenticationSettings:AuthenticationSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/johnharris85/pulumi-konnect",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AuthenticationSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AuthenticationSettings Get(string name, Input<string> id, AuthenticationSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new AuthenticationSettings(name, id, state, options);
        }
    }

    public sealed class AuthenticationSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(Optional, Boolean)** Whether basic authentication is enabled.
        /// </summary>
        [Input("basicAuthEnabled")]
        public Input<bool>? BasicAuthEnabled { get; set; }

        /// <summary>
        /// **(Optional, Boolean)** Whether IDP mapping is enabled.
        /// </summary>
        [Input("idpMappingEnabled")]
        public Input<bool>? IdpMappingEnabled { get; set; }

        /// <summary>
        /// **(Optional, Boolean)** Whether Konnect mapping is enabled.
        /// </summary>
        [Input("konnectMappingEnabled")]
        public Input<bool>? KonnectMappingEnabled { get; set; }

        /// <summary>
        /// **(Optional, Boolean)** Whether OIDC authentication is enabled.
        /// </summary>
        [Input("oidcAuthEnabled")]
        public Input<bool>? OidcAuthEnabled { get; set; }

        public AuthenticationSettingsArgs()
        {
        }
        public static new AuthenticationSettingsArgs Empty => new AuthenticationSettingsArgs();
    }

    public sealed class AuthenticationSettingsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(Optional, Boolean)** Whether basic authentication is enabled.
        /// </summary>
        [Input("basicAuthEnabled")]
        public Input<bool>? BasicAuthEnabled { get; set; }

        /// <summary>
        /// **(Optional, Boolean)** Whether IDP mapping is enabled.
        /// </summary>
        [Input("idpMappingEnabled")]
        public Input<bool>? IdpMappingEnabled { get; set; }

        /// <summary>
        /// **(Optional, Boolean)** Whether Konnect mapping is enabled.
        /// </summary>
        [Input("konnectMappingEnabled")]
        public Input<bool>? KonnectMappingEnabled { get; set; }

        /// <summary>
        /// **(Optional, Boolean)** Whether OIDC authentication is enabled.
        /// </summary>
        [Input("oidcAuthEnabled")]
        public Input<bool>? OidcAuthEnabled { get; set; }

        public AuthenticationSettingsState()
        {
        }
        public static new AuthenticationSettingsState Empty => new AuthenticationSettingsState();
    }
}
