// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace johnharris85.Konnect
{
    public static class GetRuntimeGroup
    {
        /// <summary>
        /// Represents a runtime group
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Konnect = Pulumi.Konnect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Konnect.GetRuntimeGroup.Invoke(new()
        ///     {
        ///         Name = "TestRuntimeGroup",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetRuntimeGroupResult> InvokeAsync(GetRuntimeGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRuntimeGroupResult>("konnect:index/getRuntimeGroup:getRuntimeGroup", args ?? new GetRuntimeGroupArgs(), options.WithDefaults());

        /// <summary>
        /// Represents a runtime group
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Konnect = Pulumi.Konnect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Konnect.GetRuntimeGroup.Invoke(new()
        ///     {
        ///         Name = "TestRuntimeGroup",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetRuntimeGroupResult> Invoke(GetRuntimeGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRuntimeGroupResult>("konnect:index/getRuntimeGroup:getRuntimeGroup", args ?? new GetRuntimeGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRuntimeGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// **(Optional, String)** The filter string to apply to the name of the runtime group. Uses equality.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// **(Optional, String)** The search string to apply to the name of the runtime group. Uses contains.
        /// </summary>
        [Input("searchName")]
        public string? SearchName { get; set; }

        public GetRuntimeGroupArgs()
        {
        }
        public static new GetRuntimeGroupArgs Empty => new GetRuntimeGroupArgs();
    }

    public sealed class GetRuntimeGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// **(Optional, String)** The filter string to apply to the name of the runtime group. Uses equality.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// **(Optional, String)** The search string to apply to the name of the runtime group. Uses contains.
        /// </summary>
        [Input("searchName")]
        public Input<string>? SearchName { get; set; }

        public GetRuntimeGroupInvokeArgs()
        {
        }
        public static new GetRuntimeGroupInvokeArgs Empty => new GetRuntimeGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetRuntimeGroupResult
    {
        /// <summary>
        /// **(String)** The cluster type of the runtime group.
        /// </summary>
        public readonly string ClusterType;
        /// <summary>
        /// **(String)** The control plane endpoint URL of the runtime group.
        /// </summary>
        public readonly string ControlPlaneEndpoint;
        /// <summary>
        /// **(String)** The description of the runtime group.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? Name;
        public readonly string? SearchName;
        /// <summary>
        /// **(String)** The telemetry endpoint URL of the runtime group.
        /// </summary>
        public readonly string TelemetryEndpoint;

        [OutputConstructor]
        private GetRuntimeGroupResult(
            string clusterType,

            string controlPlaneEndpoint,

            string description,

            string id,

            string? name,

            string? searchName,

            string telemetryEndpoint)
        {
            ClusterType = clusterType;
            ControlPlaneEndpoint = controlPlaneEndpoint;
            Description = description;
            Id = id;
            Name = name;
            SearchName = searchName;
            TelemetryEndpoint = telemetryEndpoint;
        }
    }
}
