// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace johnharris85.Konnect
{
    /// <summary>
    /// Represents a runtime group
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Konnect = johnharris85.Konnect;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Konnect.RuntimeGroup("example", new()
    ///     {
    ///         Description = "TestRuntimeGroup",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Runtime groups can be imported using a proper value of `id` as described above
    /// </summary>
    [KonnectResourceType("konnect:index/runtimeGroup:RuntimeGroup")]
    public partial class RuntimeGroup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// **(String)** The cluster type of the runtime group.
        /// </summary>
        [Output("clusterType")]
        public Output<string> ClusterType { get; private set; } = null!;

        /// <summary>
        /// **(String)** The control plane endpoint URL of the runtime group.
        /// </summary>
        [Output("controlPlaneEndpoint")]
        public Output<string> ControlPlaneEndpoint { get; private set; } = null!;

        /// <summary>
        /// **(Optional, String)** The description of the runtime group.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// **(Required, String)** The name of the runtime group.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// **(String)** The telemetry endpoint URL of the runtime group.
        /// </summary>
        [Output("telemetryEndpoint")]
        public Output<string> TelemetryEndpoint { get; private set; } = null!;


        /// <summary>
        /// Create a RuntimeGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RuntimeGroup(string name, RuntimeGroupArgs? args = null, CustomResourceOptions? options = null)
            : base("konnect:index/runtimeGroup:RuntimeGroup", name, args ?? new RuntimeGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RuntimeGroup(string name, Input<string> id, RuntimeGroupState? state = null, CustomResourceOptions? options = null)
            : base("konnect:index/runtimeGroup:RuntimeGroup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/johnharris85/pulumi-konnect",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RuntimeGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RuntimeGroup Get(string name, Input<string> id, RuntimeGroupState? state = null, CustomResourceOptions? options = null)
        {
            return new RuntimeGroup(name, id, state, options);
        }
    }

    public sealed class RuntimeGroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(Optional, String)** The description of the runtime group.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// **(Required, String)** The name of the runtime group.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public RuntimeGroupArgs()
        {
        }
        public static new RuntimeGroupArgs Empty => new RuntimeGroupArgs();
    }

    public sealed class RuntimeGroupState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// **(String)** The cluster type of the runtime group.
        /// </summary>
        [Input("clusterType")]
        public Input<string>? ClusterType { get; set; }

        /// <summary>
        /// **(String)** The control plane endpoint URL of the runtime group.
        /// </summary>
        [Input("controlPlaneEndpoint")]
        public Input<string>? ControlPlaneEndpoint { get; set; }

        /// <summary>
        /// **(Optional, String)** The description of the runtime group.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// **(Required, String)** The name of the runtime group.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// **(String)** The telemetry endpoint URL of the runtime group.
        /// </summary>
        [Input("telemetryEndpoint")]
        public Input<string>? TelemetryEndpoint { get; set; }

        public RuntimeGroupState()
        {
        }
        public static new RuntimeGroupState Empty => new RuntimeGroupState();
    }
}
