// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace johnharris85.Konnect.Outputs
{

    [OutputType]
    public sealed class GetNodesNodeResult
    {
        /// <summary>
        /// **(String)** Hash of the current configuration state of node.
        /// </summary>
        public readonly string ConfigHash;
        /// <summary>
        /// **(String)** Id of certificate used in communication between node and runtime group.
        /// </summary>
        public readonly string DataPlaneCertId;
        /// <summary>
        /// **(String)** Hostname of node.
        /// </summary>
        public readonly string Hostname;
        /// <summary>
        /// **(String)** Id of node.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// **(Integer)** Last time of ping of node.
        /// </summary>
        public readonly int LastPing;
        /// <summary>
        /// **(String)** Type of node.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// **(String)** Version of node.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetNodesNodeResult(
            string configHash,

            string dataPlaneCertId,

            string hostname,

            string id,

            int lastPing,

            string type,

            string version)
        {
            ConfigHash = configHash;
            DataPlaneCertId = dataPlaneCertId;
            Hostname = hostname;
            Id = id;
            LastPing = lastPing;
            Type = type;
            Version = version;
        }
    }
}
