// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace johnharris85.Konnect.Outputs
{

    [OutputType]
    public sealed class TeamMappingsMapping
    {
        /// <summary>
        /// **(Required, String)** Identifier of an IdP group that is contained with OIDC ID token for groups claim
        /// </summary>
        public readonly string Group;
        /// <summary>
        /// **(Required, List of String)** Konnect teams that should map to this group.
        /// </summary>
        public readonly ImmutableArray<string> TeamIds;

        [OutputConstructor]
        private TeamMappingsMapping(
            string group,

            ImmutableArray<string> teamIds)
        {
            Group = group;
            TeamIds = teamIds;
        }
    }
}
