// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package konnect

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/johnharris85/pulumi-konnect/sdk/go/konnect/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "konnect:index/authenticationSettings:AuthenticationSettings":
		r = &AuthenticationSettings{}
	case "konnect:index/consumer:Consumer":
		r = &Consumer{}
	case "konnect:index/identityProvider:IdentityProvider":
		r = &IdentityProvider{}
	case "konnect:index/plugin:Plugin":
		r = &Plugin{}
	case "konnect:index/route:Route":
		r = &Route{}
	case "konnect:index/runtimeGroup:RuntimeGroup":
		r = &RuntimeGroup{}
	case "konnect:index/service:Service":
		r = &Service{}
	case "konnect:index/team:Team":
		r = &Team{}
	case "konnect:index/teamMappings:TeamMappings":
		r = &TeamMappings{}
	case "konnect:index/teamRole:TeamRole":
		r = &TeamRole{}
	case "konnect:index/teamUser:TeamUser":
		r = &TeamUser{}
	case "konnect:index/user:User":
		r = &User{}
	case "konnect:index/userRole:UserRole":
		r = &UserRole{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:konnect" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"konnect",
		"index/authenticationSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/consumer",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/identityProvider",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/plugin",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/route",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/runtimeGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/service",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/team",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/teamMappings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/teamRole",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/teamUser",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"konnect",
		"index/userRole",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"konnect",
		&pkg{version},
	)
}
