# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .authentication_settings import *
from .consumer import *
from .get_consumer import *
from .get_nodes import *
from .get_role import *
from .get_runtime_group import *
from .get_team import *
from .get_team_role import *
from .get_user import *
from .get_user_role import *
from .identity_provider import *
from .plugin import *
from .provider import *
from .route import *
from .runtime_group import *
from .service import *
from .team import *
from .team_mappings import *
from .team_role import *
from .team_user import *
from .user import *
from .user_role import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import johnharris85_konnect.config as __config
    config = __config
else:
    config = _utilities.lazy_import('johnharris85_konnect.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "konnect",
  "mod": "index/authenticationSettings",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/authenticationSettings:AuthenticationSettings": "AuthenticationSettings"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/consumer",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/consumer:Consumer": "Consumer"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/identityProvider",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/identityProvider:IdentityProvider": "IdentityProvider"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/plugin",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/plugin:Plugin": "Plugin"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/route",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/route:Route": "Route"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/runtimeGroup",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/runtimeGroup:RuntimeGroup": "RuntimeGroup"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/service",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/service:Service": "Service"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/team",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/team:Team": "Team"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/teamMappings",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/teamMappings:TeamMappings": "TeamMappings"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/teamRole",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/teamRole:TeamRole": "TeamRole"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/teamUser",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/teamUser:TeamUser": "TeamUser"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/user",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/user:User": "User"
  }
 },
 {
  "pkg": "konnect",
  "mod": "index/userRole",
  "fqn": "johnharris85_konnect",
  "classes": {
   "konnect:index/userRole:UserRole": "UserRole"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "konnect",
  "token": "pulumi:providers:konnect",
  "fqn": "johnharris85_konnect",
  "class": "Provider"
 }
]
"""
)
