# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'RouteHeaderArgs',
    'TeamMappingsMappingArgs',
]

@pulumi.input_type
class RouteHeaderArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 values: pulumi.Input[Sequence[pulumi.Input[str]]]):
        """
        :param pulumi.Input[str] name: **(Required, String)** Name of header this route should require.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] values: **(Required, List of String)** Allowed values this header should equal.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "values", values)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        **(Required, String)** Name of header this route should require.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def values(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        """
        **(Required, List of String)** Allowed values this header should equal.
        """
        return pulumi.get(self, "values")

    @values.setter
    def values(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "values", value)


@pulumi.input_type
class TeamMappingsMappingArgs:
    def __init__(__self__, *,
                 group: pulumi.Input[str],
                 team_ids: pulumi.Input[Sequence[pulumi.Input[str]]]):
        """
        :param pulumi.Input[str] group: **(Required, String)** Identifier of an IdP group that is contained with OIDC ID token for groups claim
        :param pulumi.Input[Sequence[pulumi.Input[str]]] team_ids: **(Required, List of String)** Konnect teams that should map to this group.
        """
        pulumi.set(__self__, "group", group)
        pulumi.set(__self__, "team_ids", team_ids)

    @property
    @pulumi.getter
    def group(self) -> pulumi.Input[str]:
        """
        **(Required, String)** Identifier of an IdP group that is contained with OIDC ID token for groups claim
        """
        return pulumi.get(self, "group")

    @group.setter
    def group(self, value: pulumi.Input[str]):
        pulumi.set(self, "group", value)

    @property
    @pulumi.getter(name="teamIds")
    def team_ids(self) -> pulumi.Input[Sequence[pulumi.Input[str]]]:
        """
        **(Required, List of String)** Konnect teams that should map to this group.
        """
        return pulumi.get(self, "team_ids")

    @team_ids.setter
    def team_ids(self, value: pulumi.Input[Sequence[pulumi.Input[str]]]):
        pulumi.set(self, "team_ids", value)


