# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['TeamUserArgs', 'TeamUser']

@pulumi.input_type
class TeamUserArgs:
    def __init__(__self__, *,
                 team_id: pulumi.Input[str],
                 user_id: pulumi.Input[str]):
        """
        The set of arguments for constructing a TeamUser resource.
        :param pulumi.Input[str] team_id: **(Required, ForceNew, String)** The id of the team.
        :param pulumi.Input[str] user_id: **(Required, ForceNew, String)** The id of the user.
        """
        pulumi.set(__self__, "team_id", team_id)
        pulumi.set(__self__, "user_id", user_id)

    @property
    @pulumi.getter(name="teamId")
    def team_id(self) -> pulumi.Input[str]:
        """
        **(Required, ForceNew, String)** The id of the team.
        """
        return pulumi.get(self, "team_id")

    @team_id.setter
    def team_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "team_id", value)

    @property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Input[str]:
        """
        **(Required, ForceNew, String)** The id of the user.
        """
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "user_id", value)


@pulumi.input_type
class _TeamUserState:
    def __init__(__self__, *,
                 team_id: Optional[pulumi.Input[str]] = None,
                 user_id: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering TeamUser resources.
        :param pulumi.Input[str] team_id: **(Required, ForceNew, String)** The id of the team.
        :param pulumi.Input[str] user_id: **(Required, ForceNew, String)** The id of the user.
        """
        if team_id is not None:
            pulumi.set(__self__, "team_id", team_id)
        if user_id is not None:
            pulumi.set(__self__, "user_id", user_id)

    @property
    @pulumi.getter(name="teamId")
    def team_id(self) -> Optional[pulumi.Input[str]]:
        """
        **(Required, ForceNew, String)** The id of the team.
        """
        return pulumi.get(self, "team_id")

    @team_id.setter
    def team_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "team_id", value)

    @property
    @pulumi.getter(name="userId")
    def user_id(self) -> Optional[pulumi.Input[str]]:
        """
        **(Required, ForceNew, String)** The id of the user.
        """
        return pulumi.get(self, "user_id")

    @user_id.setter
    def user_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "user_id", value)


class TeamUser(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 team_id: Optional[pulumi.Input[str]] = None,
                 user_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Represents a member of a team
        ## Example Usage

        ```python
        import pulumi
        import johnharris85_konnect as konnect
        import pulumi_konnect as konnect

        team = konnect.Team("team", description="testing")
        user = konnect.get_user(search_full_name="Joe")
        example = konnect.TeamUser("example",
            team_id=team.id,
            user_id=user.id)
        ```

        ## Import

        Team users can be imported using a proper value of `id` as described above

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] team_id: **(Required, ForceNew, String)** The id of the team.
        :param pulumi.Input[str] user_id: **(Required, ForceNew, String)** The id of the user.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TeamUserArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Represents a member of a team
        ## Example Usage

        ```python
        import pulumi
        import johnharris85_konnect as konnect
        import pulumi_konnect as konnect

        team = konnect.Team("team", description="testing")
        user = konnect.get_user(search_full_name="Joe")
        example = konnect.TeamUser("example",
            team_id=team.id,
            user_id=user.id)
        ```

        ## Import

        Team users can be imported using a proper value of `id` as described above

        :param str resource_name: The name of the resource.
        :param TeamUserArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TeamUserArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 team_id: Optional[pulumi.Input[str]] = None,
                 user_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TeamUserArgs.__new__(TeamUserArgs)

            if team_id is None and not opts.urn:
                raise TypeError("Missing required property 'team_id'")
            __props__.__dict__["team_id"] = team_id
            if user_id is None and not opts.urn:
                raise TypeError("Missing required property 'user_id'")
            __props__.__dict__["user_id"] = user_id
        super(TeamUser, __self__).__init__(
            'konnect:index/teamUser:TeamUser',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            team_id: Optional[pulumi.Input[str]] = None,
            user_id: Optional[pulumi.Input[str]] = None) -> 'TeamUser':
        """
        Get an existing TeamUser resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] team_id: **(Required, ForceNew, String)** The id of the team.
        :param pulumi.Input[str] user_id: **(Required, ForceNew, String)** The id of the user.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _TeamUserState.__new__(_TeamUserState)

        __props__.__dict__["team_id"] = team_id
        __props__.__dict__["user_id"] = user_id
        return TeamUser(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="teamId")
    def team_id(self) -> pulumi.Output[str]:
        """
        **(Required, ForceNew, String)** The id of the team.
        """
        return pulumi.get(self, "team_id")

    @property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[str]:
        """
        **(Required, ForceNew, String)** The id of the user.
        """
        return pulumi.get(self, "user_id")

