// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Represents a role assigned to a user
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@pulumi/konnect";
 *
 * const user = konnect.getUser({
 *     searchFullName: "Joe",
 * });
 * const example = user.then(user => konnect.getUserRole({
 *     userId: user.id,
 *     entityTypeDisplayName: "Runtime Groups",
 * }));
 * ```
 */
export function getUserRole(args: GetUserRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetUserRoleResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("konnect:index/getUserRole:getUserRole", {
        "entityTypeDisplayName": args.entityTypeDisplayName,
        "roleDisplayName": args.roleDisplayName,
        "searchEntityTypeDisplayName": args.searchEntityTypeDisplayName,
        "searchRoleDisplayName": args.searchRoleDisplayName,
        "userId": args.userId,
    }, opts);
}

/**
 * A collection of arguments for invoking getUserRole.
 */
export interface GetUserRoleArgs {
    /**
     * **(Optional, String)** The filter string to apply to the display name of the entity type. Must be `Runtime Groups` or `Services`. Uses equality.
     */
    entityTypeDisplayName?: string;
    /**
     * **(Optional, String)** The filter string to apply to the display name of the role. Uses equality.
     */
    roleDisplayName?: string;
    /**
     * **(Optional, String)** The search string to apply to the display name of the entity type, like `Runtime Groups` or `Services`. Uses contains.
     */
    searchEntityTypeDisplayName?: string;
    /**
     * **(Optional, String)** The search string to apply to the display name of the role. Uses contains.
     */
    searchRoleDisplayName?: string;
    /**
     * **(Required, String)** The id of the user assigned the role
     */
    userId: string;
}

/**
 * A collection of values returned by getUserRole.
 */
export interface GetUserRoleResult {
    /**
     * **(String)** The id of the entity for which the role applies.
     */
    readonly entityId: string;
    /**
     * **(String)** The region of the entity for which the role applies.
     */
    readonly entityRegion: string;
    readonly entityTypeDisplayName?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly roleDisplayName?: string;
    readonly searchEntityTypeDisplayName?: string;
    readonly searchRoleDisplayName?: string;
    readonly userId: string;
}
/**
 * Represents a role assigned to a user
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as konnect from "@pulumi/konnect";
 *
 * const user = konnect.getUser({
 *     searchFullName: "Joe",
 * });
 * const example = user.then(user => konnect.getUserRole({
 *     userId: user.id,
 *     entityTypeDisplayName: "Runtime Groups",
 * }));
 * ```
 */
export function getUserRoleOutput(args: GetUserRoleOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetUserRoleResult> {
    return pulumi.output(args).apply((a: any) => getUserRole(a, opts))
}

/**
 * A collection of arguments for invoking getUserRole.
 */
export interface GetUserRoleOutputArgs {
    /**
     * **(Optional, String)** The filter string to apply to the display name of the entity type. Must be `Runtime Groups` or `Services`. Uses equality.
     */
    entityTypeDisplayName?: pulumi.Input<string>;
    /**
     * **(Optional, String)** The filter string to apply to the display name of the role. Uses equality.
     */
    roleDisplayName?: pulumi.Input<string>;
    /**
     * **(Optional, String)** The search string to apply to the display name of the entity type, like `Runtime Groups` or `Services`. Uses contains.
     */
    searchEntityTypeDisplayName?: pulumi.Input<string>;
    /**
     * **(Optional, String)** The search string to apply to the display name of the role. Uses contains.
     */
    searchRoleDisplayName?: pulumi.Input<string>;
    /**
     * **(Required, String)** The id of the user assigned the role
     */
    userId: pulumi.Input<string>;
}
